### ISSUE TITLE
Function 'LogSoftmaxBackward' returned nan values in its 0th output.

### ISSUE THREAD

**Issue by G200005** [JeonJaeHyeong/DPL#9]
Hi, I'm not sure if it's because I changed the code when dealing with the ‘Feild attributes not found “ issue that the code now has a new problem with the error message stating that Function ”LogSoftmaxBackward’ returned nan values in its 0th output. I don't know how to modify it, thank you very much for your reply.
![image](https://github.com/user-attachments/assets/cd80ec68-c6c2-4038-8938-c06e7a33d47d)

**Comment by JeonJaeHyeong** [comment]
I don’t think this error is related to fixing the attribute error. If you could let me know the command you used to run it, I’ll take a look and let you know what might be causing the issue. Thank you.

**Comment by G200005** [comment]
Hello, I sincerely thank you for your response to my question.I used the following commands to train the model on the GQA dataset and scripted the following commands to run. Could you please help me to see if there is any problem in running it this way, by comparing the training script you provided, I suspect that the problem lies in ‘GLOBAL_SETTING.BASIC_ENCODER Motifs’, and whether this command is not required when performing model training on GQA dataset.

export OMP_NUM_THREADS=1
export gpu_num=1
export EXP=checkpoints
OUTPATH=$EXP/GQA/motif/sgdet/DPL
mkdir -p $OUTPATH

CUDA_VISIBLE_DEVICES=1 python tools/relation_train_net.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" \
MODEL.ROI_RELATION_HEAD.USE_GT_BOX False \
MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False \
OUTPUT_DIR "checkpoints/GQA/motif/sgdet/DPL" \
MODEL.ROI_RELATION_HEAD.PREDICTOR MotifsLikePredictor_DPL \
GLOBAL_SETTING.BASIC_ENCODER Motifs \
SOLVER.IMS_PER_BATCH $((3*$gpu_num)) \
TEST.IMS_PER_BATCH $((gpu_num)) \
SOLVER.MAX_ITER 60000 \
SOLVER.VAL_PERIOD 2000 \
SOLVER.CHECKPOINT_PERIOD 2000 \
MODEL.ROI_RELATION_HEAD.DPL.N_DIM 128 \
MODEL.ROI_RELATION_HEAD.DPL.ALPHA 10 \
MODEL.ROI_RELATION_HEAD.DPL.AVG_NUM_SAMPLE 20 \
MODEL.ROI_RELATION_HEAD.DPL.RADIUS 1.0 \
GLOBAL_SETTING.DATASET_CHOICE "GQA_200"

**Comment by JeonJaeHyeong** [comment]
When I ran it, no issues occurred. It might help to try cloning the repository again, and if the problem still persists, please let me know. Also, I’m curious if this issue only occurs with GQA or if it also happens with VG. Thank you.

**Comment by G200005** [comment]
I cloned the repository again and tried to train using the GQA training script you provided but got the following error.But I don't have a similar problem when I train with the script you provided for the VG dataset.

subprocess.CalledProcessError: Command '['/data1/anaconda3/envs/dpl/bin/python', '-u', 'tools/relation_train_net.py', '--local_rank=0', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'False', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'False', 'OUTPUT_DIR', 'checkpoints/GQA/motif/sgdet/put_exp_name', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'MotifsLikePredictor_DPL', 'SOLVER.IMS_PER_BATCH', '3', 'TEST.IMS_PER_BATCH', '1', 'SOLVER.MAX_ITER', '60000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'MODEL.ROI_RELATION_HEAD.DPL.N_DIM', '128', 'MODEL.ROI_RELATION_HEAD.DPL.ALPHA', '10', 'MODEL.ROI_RELATION_HEAD.DPL.NUM_SAMPLE', '20', 'MODEL.ROI_RELATION_HEAD.DPL.RADIUS', '1.0', 'GLOBAL_SETTING.DATASET_CHOICE', 'GQA_200']' returned non-zero exit status 1.

**Comment by G200005** [comment]
Sorry, when I re-cloned the repository and made another attempt following the training script you provided I found some errors on the VG dataset as well, when Start validating the following error occurs.
INFO:pysgg:Model inference time: 0:03:46.798209 (0.0907192834854126 s / img per device, on 2 devices)
creating index...
index created!
Loading and preparing results...
Converting ndarray to lists...
(62754, 7)
0/62754
DONE (t=0.38s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=21.32s).
Accumulating evaluation results...
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 650, in <module>
    main()
  File "tools/relation_train_net.py", line 642, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/relation_train_net.py", line 436, in train
    val_result = run_val(cfg, model, val_data_loaders, distributed, logger)
  File "tools/relation_train_net.py", line 502, in run_val
    dataset_result = inference(
  File "/data5/2022/gym/DPL/pysgg/engine/inference.py", line 158, in inference
    return evaluate(cfg=cfg,
  File "/data5/2022/gym/DPL/pysgg/data/datasets/evaluation/__init__.py", line 29, in evaluate
    return vg_evaluation(**args)
  File "/data5/2022/gym/DPL/pysgg/data/datasets/evaluation/vg/__init__.py", line 13, in vg_evaluation
    return do_vg_evaluation(
  File "/data5/2022/gym/DPL/pysgg/data/datasets/evaluation/vg/vg_eval.py", line 131, in do_vg_evaluation
    coco_eval.accumulate()
  File "/data1/miniconda3/envs/dpl/lib/python3.8/site-packages/pycocotools-2.0-py3.8-linux-x86_64.egg/pycocotools/cocoeval.py", line 378, in accumulate
    tp_sum = np.cumsum(tps, axis=1).astype(dtype=np.float)
  File "/data1/miniconda3/envs/dpl/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Killing subprocess 59936
Killing subprocess 59937
Traceback (most recent call last):
  File "/data1/miniconda3/envs/dpl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/miniconda3/envs/dpl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data1/miniconda3/envs/dpl/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/data1/miniconda3/envs/dpl/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/data1/miniconda3/envs/dpl/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/data1/miniconda3/envs/dpl/bin/python', '-u', 'tools/relation_train_net.py', '--local_rank=1', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'True', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'True', 'OUTPUT_DIR', 'checkpoints/VG/motif/predcls/put_exp_name', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'MotifsLikePredictor_DPL', 'GLOBAL_SETTING.BASIC_ENCODER', 'Motifs', 'SOLVER.IMS_PER_BATCH', '6', 'TEST.IMS_PER_BATCH', '2', 'SOLVER.MAX_ITER', '60000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'MODEL.ROI_RELATION_HEAD.DPL.N_DIM', '128', 'MODEL.ROI_RELATION_HEAD.DPL.ALPHA', '10', 'MODEL.ROI_RELATION_HEAD.DPL.AVG_NUM_SAMPLE', '20', 'MODEL.ROI_RELATION_HEAD.DPL.RADIUS', '1.0', 'GLOBAL_SETTING.DATASET_CHOICE', 'VG']' returned non-zero exit status 1.

**Comment by JeonJaeHyeong** [comment]
The np.float-related error should be resolved by running pip install numpy==1.23.0. Please try it and let me know if it works.

**Comment by G200005** [comment]
1. Hello, I am very sorry that I have taken so long to reply to your message.According to your comments, using the pip install numpy==1.23.0 command does work, and the precls task on the GQA dataset can be executed normally, but the following problem is encountered when executing the sgcls task.
![image](https://github.com/user-attachments/assets/55513c37-d13d-4bd9-a066-b61c52a2b8cd)
I'm still using the training script commands you provided, only changing the  number of the GPU device.

2. Also, I'm having some rather strange issues with training the sgdet task on the GQA dataset, the maximum number of iterations is 60000, but why would it be more than 60000? The model also automatically saves the model_final.pth file at the 60,000th iteration of training, but the training doesn't stop, which puzzles me.
![image](https://github.com/user-attachments/assets/7a9606d7-f846-4cc5-9618-0550065a8916)
When I still execute the rel_train_gqa_sgdet.sh file you provided on a different device, but it automatically stops the training after only 54,000 iterations, and does not save the model_fianl.pth file, and does not show an error message. Why did it stop?
![image](https://github.com/user-attachments/assets/be58c618-f904-4019-84a9-3d26490b0a70)

3. The following error message appears when using the rel_test.sh you provided.
![image](https://github.com/user-attachments/assets/25dba0b7-61d1-417b-832b-ce1dfb751176)

**Comment by JeonJaeHyeong** [comment]
I've had a busy schedule recently, so I couldn't respond to your question promptly. I will get back to you by the end of November at the latest. Thank you for your patience.

**Comment by JeonJaeHyeong** [comment]
Thank you for always showing interest. Firstly, I have resolved the first error, so please check it. Regarding the second issue related to max_iteration, I'm not entirely sure. Since I used the existing code as is, I'm not sure why that part is problematic. However, if the training continues indefinitely, I suggest you stop it manually. As for why the training stops before reaching max_iteration, the model terminates automatically when the loss no longer decreases significantly. If the message "Trigger MAX_DECAY_STEP at iteration" repeats a certain number of times, the model will stop automatically.

If you encounter any errors or have any questions, feel free to ask. Thank you!
